// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/account/forgot-password": {
    params: {};
  };
  "/account/logout": {
    params: {};
  };
  "/account/resend-verification": {
    params: {};
  };
  "/account/set-password": {
    params: {};
  };
  "/account/signin": {
    params: {};
  };
  "/account/signup": {
    params: {};
  };
  "/account/verify-email": {
    params: {};
  };
  "/admin/classes": {
    params: {};
  };
  "/admin/communications": {
    params: {};
  };
  "/admin/dashboard": {
    params: {};
  };
  "/admin/homework": {
    params: {};
  };
  "/admin/payments": {
    params: {};
  };
  "/admin/pricing": {
    params: {};
  };
  "/admin/settings": {
    params: {};
  };
  "/admin/setup": {
    params: {};
  };
  "/admin/students": {
    params: {};
  };
  "/admin/teachers": {
    params: {};
  };
  "/admin/users": {
    params: {};
  };
  "/blog": {
    params: {};
  };
  "/book": {
    params: {};
  };
  "/checkout": {
    params: {};
  };
  "/choose-plan": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/my-bookings": {
    params: {};
  };
  "/my-plan": {
    params: {};
  };
  "/payment": {
    params: {};
  };
  "/payments": {
    params: {};
  };
  "/pricing": {
    params: {};
  };
  "/settings": {
    params: {};
  };
  "/thank-you": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/about" | "/account/forgot-password" | "/account/logout" | "/account/resend-verification" | "/account/set-password" | "/account/signin" | "/account/signup" | "/account/verify-email" | "/admin/classes" | "/admin/communications" | "/admin/dashboard" | "/admin/homework" | "/admin/payments" | "/admin/pricing" | "/admin/settings" | "/admin/setup" | "/admin/students" | "/admin/teachers" | "/admin/users" | "/blog" | "/book" | "/checkout" | "/choose-plan" | "/contact" | "/dashboard" | "/my-bookings" | "/my-plan" | "/payment" | "/payments" | "/pricing" | "/settings" | "/thank-you" | "/verify-email";
  };
  "./page.jsx": {
    id: "page";
    page: "/";
  };
  "./about/page.jsx": {
    id: "about/page";
    page: "/about";
  };
  "./account/forgot-password/page.jsx": {
    id: "account/forgot-password/page";
    page: "/account/forgot-password";
  };
  "./account/logout/page.jsx": {
    id: "account/logout/page";
    page: "/account/logout";
  };
  "./account/resend-verification/page.jsx": {
    id: "account/resend-verification/page";
    page: "/account/resend-verification";
  };
  "./account/set-password/page.jsx": {
    id: "account/set-password/page";
    page: "/account/set-password";
  };
  "./account/signin/page.jsx": {
    id: "account/signin/page";
    page: "/account/signin";
  };
  "./account/signup/page.jsx": {
    id: "account/signup/page";
    page: "/account/signup";
  };
  "./account/verify-email/page.jsx": {
    id: "account/verify-email/page";
    page: "/account/verify-email";
  };
  "./admin/classes/page.jsx": {
    id: "admin/classes/page";
    page: "/admin/classes";
  };
  "./admin/communications/page.jsx": {
    id: "admin/communications/page";
    page: "/admin/communications";
  };
  "./admin/dashboard/page.jsx": {
    id: "admin/dashboard/page";
    page: "/admin/dashboard";
  };
  "./admin/homework/page.jsx": {
    id: "admin/homework/page";
    page: "/admin/homework";
  };
  "./admin/payments/page.jsx": {
    id: "admin/payments/page";
    page: "/admin/payments";
  };
  "./admin/pricing/page.jsx": {
    id: "admin/pricing/page";
    page: "/admin/pricing";
  };
  "./admin/settings/page.jsx": {
    id: "admin/settings/page";
    page: "/admin/settings";
  };
  "./admin/setup/page.jsx": {
    id: "admin/setup/page";
    page: "/admin/setup";
  };
  "./admin/students/page.jsx": {
    id: "admin/students/page";
    page: "/admin/students";
  };
  "./admin/teachers/page.jsx": {
    id: "admin/teachers/page";
    page: "/admin/teachers";
  };
  "./admin/users/page.jsx": {
    id: "admin/users/page";
    page: "/admin/users";
  };
  "./blog/page.jsx": {
    id: "blog/page";
    page: "/blog";
  };
  "./book/page.jsx": {
    id: "book/page";
    page: "/book";
  };
  "./checkout/page.jsx": {
    id: "checkout/page";
    page: "/checkout";
  };
  "./choose-plan/page.jsx": {
    id: "choose-plan/page";
    page: "/choose-plan";
  };
  "./contact/page.jsx": {
    id: "contact/page";
    page: "/contact";
  };
  "./dashboard/page.jsx": {
    id: "dashboard/page";
    page: "/dashboard";
  };
  "./my-bookings/page.jsx": {
    id: "my-bookings/page";
    page: "/my-bookings";
  };
  "./my-plan/page.jsx": {
    id: "my-plan/page";
    page: "/my-plan";
  };
  "./payment/page.jsx": {
    id: "payment/page";
    page: "/payment";
  };
  "./payments/page.jsx": {
    id: "payments/page";
    page: "/payments";
  };
  "./pricing/page.jsx": {
    id: "pricing/page";
    page: "/pricing";
  };
  "./settings/page.jsx": {
    id: "settings/page";
    page: "/settings";
  };
  "./thank-you/page.jsx": {
    id: "thank-you/page";
    page: "/thank-you";
  };
  "./verify-email/page.jsx": {
    id: "verify-email/page";
    page: "/verify-email";
  };
};

type RouteModules = {
  "root": typeof import("./src/app/root.tsx");
  "page": typeof import("./src/app/./page.jsx");
  "about/page": typeof import("./src/app/./about/page.jsx");
  "account/forgot-password/page": typeof import("./src/app/./account/forgot-password/page.jsx");
  "account/logout/page": typeof import("./src/app/./account/logout/page.jsx");
  "account/resend-verification/page": typeof import("./src/app/./account/resend-verification/page.jsx");
  "account/set-password/page": typeof import("./src/app/./account/set-password/page.jsx");
  "account/signin/page": typeof import("./src/app/./account/signin/page.jsx");
  "account/signup/page": typeof import("./src/app/./account/signup/page.jsx");
  "account/verify-email/page": typeof import("./src/app/./account/verify-email/page.jsx");
  "admin/classes/page": typeof import("./src/app/./admin/classes/page.jsx");
  "admin/communications/page": typeof import("./src/app/./admin/communications/page.jsx");
  "admin/dashboard/page": typeof import("./src/app/./admin/dashboard/page.jsx");
  "admin/homework/page": typeof import("./src/app/./admin/homework/page.jsx");
  "admin/payments/page": typeof import("./src/app/./admin/payments/page.jsx");
  "admin/pricing/page": typeof import("./src/app/./admin/pricing/page.jsx");
  "admin/settings/page": typeof import("./src/app/./admin/settings/page.jsx");
  "admin/setup/page": typeof import("./src/app/./admin/setup/page.jsx");
  "admin/students/page": typeof import("./src/app/./admin/students/page.jsx");
  "admin/teachers/page": typeof import("./src/app/./admin/teachers/page.jsx");
  "admin/users/page": typeof import("./src/app/./admin/users/page.jsx");
  "blog/page": typeof import("./src/app/./blog/page.jsx");
  "book/page": typeof import("./src/app/./book/page.jsx");
  "checkout/page": typeof import("./src/app/./checkout/page.jsx");
  "choose-plan/page": typeof import("./src/app/./choose-plan/page.jsx");
  "contact/page": typeof import("./src/app/./contact/page.jsx");
  "dashboard/page": typeof import("./src/app/./dashboard/page.jsx");
  "my-bookings/page": typeof import("./src/app/./my-bookings/page.jsx");
  "my-plan/page": typeof import("./src/app/./my-plan/page.jsx");
  "payment/page": typeof import("./src/app/./payment/page.jsx");
  "payments/page": typeof import("./src/app/./payments/page.jsx");
  "pricing/page": typeof import("./src/app/./pricing/page.jsx");
  "settings/page": typeof import("./src/app/./settings/page.jsx");
  "thank-you/page": typeof import("./src/app/./thank-you/page.jsx");
  "verify-email/page": typeof import("./src/app/./verify-email/page.jsx");
};